//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpLearning.DecisionTrees.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpLearning.DecisionTrees.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1;F2;T
        ///1;0.409175;1.88318
        ///1;0.182603;0.063908
        ///1;0.663687;3.042257
        ///1;0.517395;2.305004
        ///1;0.013643;-0.067698
        ///1;0.469643;1.662809
        ///1;0.725426;3.275749
        ///1;0.39435;1.118077
        ///1;0.50776;2.095059
        ///1;0.237395;1.181912
        ///1;0.057534;0.221663
        ///1;0.36982;0.938453
        ///1;0.976819;4.149409
        ///1;0.616051;3.105444
        ///1;0.4137;1.896278
        ///1;0.105279;-0.121345
        ///1;0.670273;3.161652
        ///1;0.952758;4.135358
        ///1;0.272316;0.859063
        ///1;0.303697;1.170272
        ///1;0.486698;1.68796
        ///1;0.51181;1.979745
        ///1;0.195865;0.06869
        ///1;0.986769;4.052137
        ///1;0.78 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DecisionTreeData {
            get {
                return ResourceManager.GetString("DecisionTreeData", resourceCulture);
            }
        }
    }
}
