//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpLearning.InputOutput.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpLearning.InputOutput.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AptitudeTestScore;PreviousExperience_month;Pass
        ///5;6;0
        ///1;15;0
        ///1;12;0
        ///4;6;0
        ///1;15;1
        ///1;6;0
        ///4;16;1
        ///1;10;1
        ///3;12;0
        ///4;26;1
        ///5;2;1
        ///1;12;0
        ///3;18;0
        ///3;3;0
        ///1;24;1
        ///2;8;0
        ///1;9;0
        ///4;18;0
        ///4;22;1
        ///5;3;1
        ///4;12;0
        ///4;24;1
        ///2;18;1
        ///2;6;0
        ///1;8;0
        ///5;12;0
        ///.
        /// </summary>
        internal static string AptitudeTestData {
            get {
                return ResourceManager.GetString("AptitudeTestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date;Open;High;Low;Close;Volume;Adj Close
        ///2014-04-29;38.01;39.68;36.80;38.00;294200;38.00
        ///2014-04-28;38.26;39.36;37.30;37.83;361900;37.83
        ///2014-04-25;38.33;39.04;37.88;38.00;342900;38.00
        ///2014-04-24;39.33;39.59;37.91;38.82;362200;38.82
        ///2014-04-23;38.98;39.58;38.50;38.88;245800;38.88
        ///2014-04-22;38.43;39.79;38.31;38.99;358000;38.99
        ///2014-04-21;38.05;38.74;37.77;38.41;316800;38.41
        ///2014-04-17;37.25;38.24;36.92;38.05;233700;38.05
        ///2014-04-16;36.37;37.27;36.17;37.26;144800;37.26
        ///2014-04-15;36.08;36.74;35.09 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TimeData1 {
            get {
                return ResourceManager.GetString("TimeData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date;Open;High;Low;Close;Volume;Adj Close
        ///2014-05-05;20.89;20.99;20.55;20.89;62200;20.89
        ///2014-05-02;21.08;21.50;20.85;21.09;76600;21.09
        ///2014-05-01;21.17;21.28;20.62;20.97;102600;20.97
        ///2014-04-30;21.78;21.89;21.14;21.27;171800;21.27
        ///2014-04-29;22.05;22.44;21.72;21.78;81900;21.78
        ///2014-04-28;21.79;22.00;21.46;21.90;71100;21.90
        ///2014-04-25;22.10;22.48;21.67;21.78;77500;21.78
        ///2014-04-24;22.61;22.70;22.20;22.23;48700;22.23
        ///2014-04-23;22.26;22.95;22.16;22.60;99400;22.60
        ///2014-04-22;22.19;22.70;22.13;22.48; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TimeData2 {
            get {
                return ResourceManager.GetString("TimeData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date;OpenOther;High;Low;CloseOther;Volume;Adj Close
        ///2014-05-05;20.89;20.99;20.55;20.89;62200;20.89
        ///2014-05-02;21.08;21.50;20.85;21.09;76600;21.09
        ///2014-05-01;21.17;21.28;20.62;20.97;102600;20.97
        ///2014-04-30;21.78;21.89;21.14;21.27;171800;21.27
        ///2014-04-29;22.05;22.44;21.72;21.78;81900;21.78
        ///2014-04-28;21.79;22.00;21.46;21.90;71100;21.90
        ///2014-04-25;22.10;22.48;21.67;21.78;77500;21.78
        ///2014-04-24;22.61;22.70;22.20;22.23;48700;22.23
        ///2014-04-23;22.26;22.95;22.16;22.60;99400;22.60
        ///2014-04-22;22.19;22.70;22 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TimeData21 {
            get {
                return ResourceManager.GetString("TimeData21", resourceCulture);
            }
        }
    }
}
