//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpLearning.RandomForest.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpLearning.RandomForest.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AptitudeTestScore;PreviousExperience_month;Pass
        ///5;6;0
        ///1;15;0
        ///1;12;0
        ///4;6;0
        ///1;15;1
        ///1;6;0
        ///4;16;1
        ///1;10;1
        ///3;12;0
        ///4;26;1
        ///5;2;1
        ///1;12;0
        ///3;18;0
        ///3;3;0
        ///1;24;1
        ///2;8;0
        ///1;9;0
        ///4;18;0
        ///4;22;1
        ///5;3;1
        ///4;12;0
        ///4;24;1
        ///2;18;1
        ///2;6;0
        ///1;8;0
        ///5;12;0
        ///.
        /// </summary>
        internal static string AptitudeData {
            get {
                return ResourceManager.GetString("AptitudeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1;F2;F3;F4;F5;F6;F7;F8;F10;Target
        ///1.52101;13.64;4.49;1.1;71.78;0.06;8.75;0;0;1
        ///1.51761;13.89;3.6;1.36;72.73;0.48;7.83;0;0;1
        ///1.51618;13.53;3.55;1.54;72.99;0.39;7.78;0;0;1
        ///1.51766;13.21;3.69;1.29;72.61;0.57;8.22;0;0;1
        ///1.51742;13.27;3.62;1.24;73.08;0.55;8.07;0;0;1
        ///1.51596;12.79;3.61;1.62;72.97;0.64;8.07;0;0.26;1
        ///1.51743;13.3;3.6;1.14;73.09;0.58;8.17;0;0;1
        ///1.51756;13.15;3.61;1.05;73.24;0.57;8.24;0;0;1
        ///1.51918;14.04;3.58;1.37;72.08;0.56;8.3;0;0;1
        ///1.51755;13;3.6;1.36;72.99;0.57;8.4;0;0.11;1
        ///1.51571;12 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Glass {
            get {
                return ResourceManager.GetString("Glass", resourceCulture);
            }
        }
    }
}
